# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial

install:
- pip install -U wheel
- pip install -U tox
- pip install -U codecov

# command to run tests, e.g. python setup.py test
script: tox

addons:
  apt:
    packages:
      - language-pack-fr

after_success:
    - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: "Vs2Z69YTFzQWVkos7IvP4xk0RAQ35dzVXP+EAmzMkqi9qToTa7jdeF8deY18r3l8093jaJ/ct6NzjNiZ6ryWl1yKBwYoW+jaXjKGVXMFSQdqXiDreu516rqrOiRfZVHy+G9TabjhVrIW2npkxuOP7d0HONOZnNtCn6QrxQwEBzw="
  on:
    tags: true
    repo: scrapinghub/dateparser
    condition: "$TOXENV == py27"
